defaults: &defaults
  adapter: mysql2

development:
  <<: *defaults
  database: pinpoint_development

test:
  <<: *defaults
  database: pinpoint_test
  min_messages: WARNING

production:
  <<: *defaults
  database: pinpoint_development
